# Base para API de inferencia
# FROM python:3.10
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY ./serving /app/serving
# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
